# Generated by Django 4.1.4 on 2023-09-22 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food1', models.CharField(default='null', max_length=100)),
                ('drink1', models.CharField(default='null', max_length=100)),
                ('dates', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(6, message='Value must be less than or equal to 6')])),
                ('food2', models.CharField(default='null', max_length=100)),
                ('drink2', models.CharField(default='null', max_length=100)),
                ('food3', models.CharField(default='null', max_length=100)),
                ('drink3', models.CharField(default='null', max_length=100)),
                ('food4', models.CharField(default='null', max_length=100)),
                ('drink4', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eight', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='1', max_length=40)),
                ('nine', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='2', max_length=40)),
                ('ten', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='3', max_length=40)),
                ('eleven', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='4', max_length=40)),
                ('twelve', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='5', max_length=40)),
                ('one', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='6', max_length=40)),
                ('two', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='7', max_length=40)),
                ('three', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='8', max_length=40)),
                ('four', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='9', max_length=40)),
                ('five', models.CharField(choices=[('2', 'SE'), ('4', 'CN'), ('7', 'CN lab'), ('5', 'AI'), ('1', 'HPC'), ('9', 'null'), ('6', 'BIG DATA'), ('3', 'DAA'), ('8', 'DAA lab')], default='9', max_length=40)),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(6, message='Value must be less than or equal to 6')])),
            ],
        ),
    ]
