# Generated by Django 4.1.4 on 2023-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_times_eight_alter_times_eleven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='eight',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='eleven',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='4', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='five',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='four',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='nine',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='2', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='one',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='6', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='ten',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='3', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='three',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='8', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='twelve',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='5', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='two',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='7', max_length=40),
        ),
    ]
