# Generated by Django 4.1.4 on 2023-09-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_times_eight_alter_times_eleven_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='one',
            new_name='1-2',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='ten',
            new_name='10-11',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='eleven',
            new_name='11-12',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='twelve',
            new_name='12-1',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='two',
            new_name='2-3',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='three',
            new_name='3-4',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='five',
            new_name='4-5',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='four',
            new_name='5-6',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='eight',
            new_name='8-9',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='nine',
            new_name='9-10',
        ),
    ]
