# Generated by Django 4.1.4 on 2023-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_one_times_1-2_rename_ten_times_10-11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='1-2',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='10-11',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='11-12',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='12-1',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='2-3',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='3-4',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='8-9',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
        migrations.AlterField(
            model_name='times',
            name='9-10',
            field=models.CharField(choices=[('1', 'HPC'), ('2', 'SE'), ('3', 'DAA'), ('4', 'CN'), ('5', 'AI'), ('6', 'BIG DATA'), ('7', 'CN lab'), ('8', 'DAA lab'), ('9', 'null')], default='9', max_length=40),
        ),
    ]
