# Generated by Django 4.1.4 on 2023-09-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_times_1-2_alter_times_10-11_alter_times_11-12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='1-2',
            new_name='one',
        ),
    ]
