# Generated by Django 4.1.4 on 2023-09-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_1-2_times_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='10-11',
            new_name='eight',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='11-12',
            new_name='eleven',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='12-1',
            new_name='five',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='2-3',
            new_name='four',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='3-4',
            new_name='nine',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='4-5',
            new_name='ten',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='5-6',
            new_name='three',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='8-9',
            new_name='twelve',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='9-10',
            new_name='two',
        ),
    ]
