# Generated by Django 4.1.4 on 2023-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_10-11_times_eight_rename_11-12_times_eleven_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(default='null', max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
