# Generated by Django 4.1.4 on 2023-09-24 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tasks_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
