# Generated by Django 4.1.4 on 2023-10-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Dataofdaily',
        ),
    ]
